name: gitartwork from a contribution graph
on:
   push:
   schedule:
     - cron: '* */6 * * *'
  
   workflow_dispatch:
  
jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: SeiryuJP/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: SeiryuJP
            # Text on contribution graph 
            text: SEIRYU
       - uses: jasineri/simple-push-action@v1
